### ISSUE TITLE
不能debug模式么？写文件不是必须的，是否可以加个开关项

### ISSUE THREAD

**Issue by q979713444** [pqpo/Log4a#10]

**Comment by pqpo** [comment]
可以类比 LevelInterceptor 使用 Interceptor 简单实现一下。甚至可以直接使用 LevelInterceptor

**Comment by helloworld10010** [comment]
@pqpo 请问怎么写啊...  瓢不会画

**Comment by helloworld10010** [comment]
@pqpo Interceptor 里 return false就不写日志了吗？
