### ISSUE TITLE
so文件为什么这么大？

### ISSUE THREAD

**Issue by one2zero** [pqpo/Log4a#11]
以1.3.0版本的release目录下的armeabi架构来看，so文件有133K。
是有相关编译选项没有设置么，看代码不应该这么大啊。。。

**Comment by pqpo** [comment]
我这边看来 1.3.0 版本包减小了。
v1.0.0: 309kb; 
v1.1.0: 794k; 
v1.2.0: 794k; 
v1.3.0: 318k;
1.1.0, 1.2.0 现在不太清楚为什么会这么大，1.3.0 只增加了 -lz 编译项，理论上包应该更大，目前编译配置为：
cppFlags "-std=c++11 -frtti -fexceptions -lz"
刚刚试着把 -frtti -fexceptions 去掉，但是只减小了9kb。接下来我看看如何瘦身 ，你有思路的话欢迎留言。
