### ISSUE TITLE
 对iOS平台进行支持 

### ISSUE THREAD

**Issue by Coneboy-k** [pqpo/Log4a#12]
po主何不把log4a做成 Log4m   :-)

**Comment by pqpo** [comment]
对 OC 不太了解，可以一起做:-)

**Comment by Coneboy-k** [comment]
最近抽空试试~ 先从基本接口来对接

**Comment by Coneboy-k** [comment]
今天已经把C++和OC 结合起来。速度很不错，po主怎么规划iOS所在文件夹？需要我直接PR吗？

**Comment by Coneboy-k** [comment]
建议&想法
1.把写核心CPP代码进行抽离，做成一个单个git repo，然后根据不同的平台把核心代码当做进行git-submudle 整合。
2.日志如果打印的多，我们需要对文件进行切分。不能让一天的日志过于大。这时候需要对文件进行切分。我觉的这个控制，应该由上层进行实现。被基本信息通过json序列化到日志相关路径。
3.po主需要考虑的最终形态，是专注于日志的写入，还是做一个针对移动端的日志解决方案？

**Comment by pqpo** [comment]
真棒，赞一个👍。
1. 你可以建个分支先 push 一下你的代码吗？我不太清楚你那边的目录结构。如果把 cpp 核心代码放到根目录，你那能用相对路径引用到吗？
2、3. 日志过多的问题我也考虑过，cpp 层只关注安全高效的日志写入，包括已经实现的压缩功能和未实现的加密功能。至于文件分割，json序列号话这些都交给上层实现，也就是目前 Java 层通过拓展接口可以方便实现这些功能。

**Comment by Coneboy-k** [comment]
OK，最近有时间我把代码整理一下放上去，目前我的目录结构是这样的。  
![image](https://user-images.githubusercontent.com/3970260/37277325-56a349b0-261f-11e8-9609-a2c6fa41c80c.png)
考虑后续的扩展。C++考虑更新下。
1.如果切分日志，那么写日志的 logPath是可以切换的。
2.如果C++层不添加日志控制逻辑。那就得wapper层进行控制，这块影响的接口我还没想好。想好了留言把。  

另外，我这边测试，在ip6s上写入速度可以提高一个数量级。 但是老旧手机，时间差不都 :-)

**Comment by pqpo** [comment]
目前是不支持日志切换的，需要 release 掉，重新创建一个写日志对象，原因是 c++ 里用了一个静态线程线程写入日志文件。后续我会着重解决掉这个问题。

**Comment by Coneboy-k** [comment]
我的想法是，在启动日志引擎的时候，只是传入文件夹的path，命名以接口方式回调给上层，由上层填写，当然引擎也有缺省实现。
我的想法是，创建第一个日志时，同时创建第二文件，两者的结合方式，类似于单向链表。如果第一个写满，即将向第二文件时，第三文件就同时创建。下一个文件名，也可以和日志文件的路径一样，写到文件头中，注意仅写入文件头。
当然这个得抽出一个管理类了。 这仅仅是个建议~ 

我目前不会写C++，所以C++层我无能为力。 期待po主的力作  2333

**Comment by Coneboy-k** [comment]
不好意思哈，前期有点忙给忘了，这周提过去。

**Comment by Coneboy-k** [comment]
已经提交RP，详情在RP中有写。

**Comment by pqpo** [comment]
v.1.4.0 版本支持更换日志文件路径：
```java
logBuffer.changeLogPath(logPath)
```
