### ISSUE TITLE
日志完整性

### ISSUE THREAD

**Issue by xulong20130712** [pqpo/Log4a#13]
求问：
//在应用退出的时候刷新缓存
Log4a.flush();
//如果想要释放内存可以调用下面的方法，内部会调用刷新，下次使用需要重新初始化
Log4a.release();
这两个是必须调用的吗？
如果我在调用这两个之前就被系统杀掉，或者是被用户自己手动杀掉还会完整保存日志吗？

**Comment by pqpo** [comment]
两个都不是必须的，如果用户手动杀应用，日志文件还是会保存下拉，会在下次初始化 Log4a 的时候回写到日志文件中。

1. Log4a.flush(); 会主动刷新缓存，
2. Log4a.release(); 会刷新缓存并释放资源，一般在应用退出的时候调用，但是下次使用需要重新初始化。

**Comment by xulong20130712** [comment]
了解了，谢谢大神
