### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by lxz2014** [pqpo/Log4a#2]
如果日志名字是按照日期命名的，每次启动会重新生成一个新的日志文件，如果进程被强杀，再恢复上次的日志信息，都是在新建的日志文件里面的，按照我的想法是追加在上次保存文件后面的。

最后：我能集成到我们项目中应用吗？不会承担啥法律责任吧，—___—……

**Comment by pqpo** [comment]
感谢你的建议，我会考虑如何实现的。另外非常欢迎接入使用，本项目是基于 Apache License 2.0 协议开源的，可以修改发布，你可以了解下。

**Comment by pqpo** [comment]
Hi, 已经根据你的建议发布了 [v1.1.0](https://github.com/pqpo/Log4a/releases/tag/v1.1.0) 版本。再次感谢你的建议。

**Comment by pqpo** [comment]
已修改！

**Comment by lxz2014** [comment]
好的，我已经集成了你的日志框架，挺好用的，赞个
