### ISSUE TITLE
更换LogFilePath路径 缓存头文件中对应LogFilePath未改变

### ISSUE THREAD

**Issue by Android-Mainli** [pqpo/Log4a#21]
更换LogFilePath路径 缓存头文件中对应LogFilePath未改变  感觉这个时候应该把缓存文件中log写入对应log中然后重新生成缓存文件.

**Comment by pqpo** [comment]
你是测试出来没改变吗？
代码逻辑上是会 flush 缓存，然后重建缓存：
```c++
void LogBuffer::changeLogPath(char *log_path) {
    if(log_file != nullptr) {
        async_flush();
    }
    initData(log_path, strlen(log_path), is_compress);
}
```

**Comment by Android-Mainli** [comment]
是这样 首先正常初始化(初始化文件名字取得是当日日期)输出日志 而后修改手机时间更换保存名字初始化 两次初始化缓存文件使用同一份  结果后换保存文件名的日志正常写入缓存 最后脏数据会写入第一次保存名字的文件中

**Comment by pqpo** [comment]
一般在 Application 初始化 Log,  那么更换手机时间后，杀死进程，重启应用，这个时候理论上会先写脏数据，然后重建缓存。
如果要在应用使用中更换日志文件路径，那么需要手动调用一下  me.pqpo.librarylog4a.LogBuffer 的 changeLogPath();

**Comment by pqpo** [comment]
我用本项目的 DEMO 进行如下测试：
1. log content 输入：“7月10日”， 点击 WRITE LOG， 输出文件到缓存目录。
2. 杀进程，确保日志还留着缓存文件中。
3. 修改时间到 7月11日，打开应用，此时会写脏数据，然后重建缓存。按 HOME 键退到后台，然后去日志目录验证一下，打开日志文件 2018_07_10.txt 存在日志 “7月10日” ，符合预期。
4. log content 输入：“7月11日”， 点击 WRITE LOG， 点击返回退出应用，确保缓存已经刷新到日志文件中
5. 查看日志文件 2018_07_11.txt 存在日志 “7月11日”， 符合预期。

**Comment by Android-Mainli** [comment]
​
 device-2018-07-10-115950.mp4
<https://drive.google.com/file/d/1jG2w2Ly_G4eH4djK1IgfJxTvCX3SEKtN/view?usp=drive_web>
​我这边简短录了个视频

在 2018年7月10日 上午11:44，Linmin Qiu <notifications@github.com>写道：

**Comment by pqpo** [comment]
奇怪了，我按你视频里的操作了一遍是正常的，我的系统是 7.1.2

**Comment by pqpo** [comment]
#32 有可能是这个问题造成的，1.4.2 已修复
