### ISSUE TITLE
Failed to resolve: com.github  或 Failed to resolve: com.github.pqpo:Log4a:1.4.0

### ISSUE THREAD

**Issue by helloworld10010** [pqpo/Log4a#27]
是把 `maven { url 'https://jitpack.io' }`放到`project build.gradle`的`allprojects->repositories`，`compile 'com.github.pqpo:Log4a:{last-version}'`放到`module build.gradle`中 吧？   我好像个弱智?

**Comment by helloworld10010** [comment]
`Logger logger = new Logger.Builder()
                .enableAndroidAppender(androidBuild)
                .enableFileAppender(fileBuild)
                .create();`
Builder()方法报红,接口里没这函数，换成实现类的Builder()后 没有后边的enable方法了.....  我现在把你realease里的1.4aar放进去了，难道少东西了? ...

**Comment by pqpo** [comment]
是的：）
