### ISSUE TITLE
同道中人哈

### ISSUE THREAD

**Issue by Blankj** [pqpo/Log4a#3]
我之前也为我公司封装过高性能日志，也是结合了 marx 的 xlog，不过我是直接用的 xlog 编译出来的 .so库，然后结合我的 [alog](https://github.com/Blankj/ALog)，仅仅在写入文件部分使用到了 xlog 的代码，公司也一直在用我封装的 Lg，哈哈。

**Comment by pqpo** [comment]
Cool, 同道中人～，mars 是个很优秀的框架，考虑到 xlog 的有些功能暂时用不到（比如压缩，加密等），编译出来等 so 有2M左右。了解到 xlog 使用了 mmap 来代替内存缓冲，所以自己实现了一套。压缩，加密等其他功能之后考虑添加单独的模块插入到 Interceptor 中。

**Comment by Blankj** [comment]
我们只适配某一类型的设备，所以只需要一种类型的 .so 即可，500k 左右即可哈。

**Comment by pqpo** [comment]
估计是新版本包变大了，我上次仅编译了 armeabi 平台，so 文件有 1.8 m
