### ISSUE TITLE
Logger.Builder类找不到

### ISSUE THREAD

**Issue by Chen-Sir** [pqpo/Log4a#30]
README没有更新吗？
怎么个用法啊
Logger logger = new Logger.Builder()
          .enableAndroidAppender(androidBuild)
          .enableFileAppender(fileBuild)
          .create();

**Comment by dengzhao7053** [comment]
所以 正确的到底是什么呢

**Comment by leveychen** [comment]
> 所以 正确的到底是什么呢

AppenderLogger.Builder()
