### ISSUE TITLE
使用过程中有日志丢失的情况

### ISSUE THREAD

**Issue by summerzh** [pqpo/Log4a#33]
我项目中使用该日志已经有一段时间了，但是今天发现了一次日志丢失的情况。在某台设备中的昨天的日志中，时间戳只有到22：20分，到24点之间的日志没有了。而且这台设备不会在这个时间不会存在重启或者app被强行杀死的情况。请问日志丢失的问题出在哪里？

**Comment by pqpo** [comment]
https://github.com/pqpo/Log4a/issues/32 有可能是这个问题造成的，一个低级错误，1.4.2 已修复，可以再观察观察
