### ISSUE TITLE
性能比较

### ISSUE THREAD

**Issue by duanshoucheng** [pqpo/Log4a#34]
华为手机测试发现：log4a spend:35ms
file log(no buffer in thread) spend:22ms.
结果似乎FileoutputStream性能不比mmep差，当然需要开启一个线程。能解释是为什么吗

**Comment by fanxxxx** [comment]
请测试的数据量， mmap需要在数据量比较大的情况下才能看出效果。

还有使用mmap 的另一个原因是就算进程被杀，系统还是会把映射在内存里的数据写进磁盘，如果是OutputStream，这些数据就丢失了

FileOutputStream 没有buffer， 但是实际Linux系统在write时还是会有缓存的。
