### ISSUE TITLE
mmap依然是延迟写入机制

### ISSUE THREAD

**Issue by Dovar66** [pqpo/Log4a#35]
mmap也是与标准IO一样的延迟写入机制，README文档中的这段描述应该是有问题的：日志首先会写入到 mmap 文件映射内存中，基于 mmap 的特性，即使用户强杀了进程，日志文件也不会丢失。

**Comment by bylijian** [comment]
为什么我的杀进程会丢失log？？？

**Comment by Dovar66** [comment]
> 
> 
> 为什么我的杀进程会丢失log？？？

我想表达的意思就是会丢失，因为mmap是延迟写入机制

**Comment by pqpo** [comment]
mmap 是延迟写入，对于脏数据，系统会在一定的时间自动回写到磁盘中，这是系统内核保证的，与当前写入进程是否存活无关。我觉得如下描述并无问题：“即使用户强杀了进程，日志文件也不会丢失。”

**Comment by Dovar66** [comment]
> 
> 
> mmap 是延迟写入，对于脏数据，系统会在一定的时间自动回写到磁盘中，这是系统内核保证的，与当前写入进程是否存活无关。我觉得如下描述并无问题：“即使用户强杀了进程，日志文件也不会丢失。”

那请问怎么解释标准IO在强杀进程时的丢失问题？标准IO与mmap都是写入页缓存然后等待内核回收脏页

**Comment by bylijian** [comment]
@pqpo ,作者可以验证下，我的情况是，一个so库奔溃，然后，进程结束了，log丢失很多。并且不是只有这种情况，正常的退出app，或者杀进程，都会丢失，比较Android studio的输出的日志和保存到文件的log的最后一条的时间，往往差挺多的

**Comment by pqpo** [comment]
@bylijian 你这边测试是杀进程 100% 丢失日志？
杀进程不丢失日志正是这个库的主要特性，发布之前我当然也验证过。
其他 ISSUE 里也有提过偶尔出现丢失的情况，但是后面修复了。
https://github.com/pqpo/Log4a/issues/33

**Comment by pqpo** [comment]
@Dovar66 标准IO在强杀进程时的丢失问题，你指的是使用 OutputStream 写文件，然后杀进程，文件内容会丢失？这种情况不常见吧？
对比 BufferedOutputStream，缓存是直接写在内存中的，杀进程 100% 会丢失内存数据。对于 mmap 我验证的结果是：杀进程，日志会留在 mmap 文件中。
