### ISSUE TITLE
async_flush 导致日志丢失，建议新增同步的 flush 方法

### ISSUE THREAD

**Issue by zwc456baby** [pqpo/Log4a#36]
## 导致日志丢失的复现步骤(大约 10% 的概率)：
> 在自定义的 `application` 的 `onTerminate()` 生命周期中，调用 `flush()` 方法，然后底层是调用的 `async_flush` 去刷新数据的，因为 `onTerminate()` 之后，app会很快的退出，导致这个异步没有成功的 flush，所以日志文件很大概率丢失。

作者在自己的[博客文章](https://pqpo.me/2018/01/17/log4a-principle-analysis/)中也提到了这种可能性

```
良秋2018-08-21 16:24
如果请求AsyncFileFlush异步写到log_file的时候，进程被杀，是不是就丢了日志


pqpo2018-08-21 16:32回复
理论上是的，但是在缓存不是特别大的情况下写入是毫秒级的，丢日志的概率极小。
如果要优化的话在实现上得开辟更大的缓存，比如缓存扩大一倍，在写满一半的时候，开始写入前一半的缓存，但是不删除，等确保写入成功之后再标记删除缓存。
这样在实现复杂度上也会增大很多。
```

## 建议新增同步的flush 方法

原因：

如果 app  ERROR，肯定会产生大量异常日志，这时候会触发 buffer 写满，然后内部调用 `async_flush` ，而 app error 以后，又会很快的结束进程。这时候就会和上面说的一样，没有成功 flush 导致日志丢失。而 error 日志恰巧是最需要保存的。

如果新增 同步的 flush ，在error 捕获类中，flush 后再 kill 进程，则不会有这种问题

**以上**

**Comment by zwc456baby** [comment]
在 [这个 issue 中](https://github.com/pqpo/Log4a/issues/35#issuecomment-475144353)也有人提到app退出或者崩溃导致日志丢失，个人猜测应该和我说的一样，崩溃产生大量日志触发了 `async_flush` 然后没有成功写入 log_file 导致丢失

**Comment by zwc456baby** [comment]
我自己 fork 项目，新增了 sync_flush 方法，不知道这样修改是否是真正的 同步刷新，因为我修改成同步的 flush 后，对性能似乎没有影响。[查看我的forck](https://github.com/zwc456baby/Log4a)

**Comment by pqpo** [comment]
merged
