### ISSUE TITLE
集成报错

### ISSUE THREAD

**Issue by dengzhao7053** [pqpo/Log4a#37]
按照readme集成到Android项目中报错：
04-19 15:40:13.517 12844 12844 F DEBUG   : Abort message: 'java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.NoSuchMethodError: no static or non-static method "Lme/pqpo/librarylog4a/LogBuffer;.flushAsyncNative(J)V"'

请问一下 大概是什么问题呢 谢谢

**Comment by zwc456baby** [comment]
你更换手机运行了吗

**Comment by zwk1729** [comment]
我也报同样的错

**Comment by SpannerBear** [comment]
我也遇到了，是混淆之后出现的。目前解决方法是把整个库keep住

**Comment by zwc456baby** [comment]
尝试在混淆文件里面添加

```
-keep class me.pqpo.librarylog4a.LogBuffer  { *; }
```
之前在某个项目做了混淆，用了混淆配置
但暂时找不到那个配置了

**Comment by SpannerBear** [comment]
主要是native方法不能混淆
