### ISSUE TITLE
Seek help - About use

### ISSUE THREAD

**Issue by chunpingxu** [pqpo/Log4a#45]
1. compile 'com.github.pqpo:Log4a:{last-version}'
What is the last-version ?
2. init log4a： “new Logger.Builder()” ，no Builder in Logger.\
The init code: 
Logger logger = new Logger.Builder()
          .enableAndroidAppender(androidBuild)
          .enableFileAppender(fileBuild)
          .create();
          
Log4a.setLogger(logger);

mail: 773964842@qq.com

**Comment by song314** [comment]
this may be useful:

[https://github.com/pqpo/Log4a/blob/master/app/src/main/java/me/pqpo/log4a/LogInit.java](url)
