### ISSUE TITLE
本来想用的，但是..

### ISSUE THREAD

**Issue by Trumeet** [pqpo/Log4a#6]
哈哈标题党了（x
本来看非常不错，正合我需要，但是发现有 native，就放弃了，嫌 native 太大..
我不懂 native，有没有不需要 native 的方法呢..

**Comment by pqpo** [comment]
现在提供的 aar 文件为 700+k，包括了 x86, mips, armeabi, armeabi-v7a, 接入的时候加上 
```
ndk {
     abiFilters 'armeabi'
}
```
最终只会增加不到 200k

**Comment by Trumeet** [comment]
哦，那就好，感谢作者
