### ISSUE TITLE
日志打印支持多进程么？

### ISSUE THREAD

**Issue by lightai** [pqpo/Log4a#7]
Android架构，一个app很可能同时开启多进程。

**Comment by pqpo** [comment]
mmap 本身是支持多进程访问的，比如一个读，一个写。但是如果同时写的话是无法保证进程同步写。解决方法就是不同的进程使用不同的 BufferFilePath ，文件名中加入进程 id，或者进程 id 的 md5 值。

**Comment by lightai** [comment]
好的，刚刚也是想到这么做。
如果能加上进程同步的feature也不错，也许某些情况写到一个文件更容易定位问题。
mars的xlog貌似也不支持多进程写同一个日志。

**Comment by pqpo** [comment]
嗯，非常不错的 ISSUE，之前我也没考虑到多进程的问题。我再查查资料，看看如何是否可以做进程间的同步锁。
另外补充一点，C 的 write 加入 O_APPEND 标志位后是支持多进程同时读写的，多进程下的 log 文件是可以设置成同一个的，只是写文件的行顺序会不可避免的出现交叉的现象。但是读写 mmap 的时候使用了线程锁，所以就不支持多进程同步读写了。

**Comment by lightai** [comment]
赞👍

**Comment by lightai** [comment]
进程锁除了文件锁可以用，其他信号量、mutex、共享变量有进程异常退出无法清理导致死锁问题。
目前可以参考的方案是sqlite多进程同步的方案：fcntl+busyhandler的方式。

进程同步能够很好解决的话，扩展开来，Android的SharedPreferences可以替换为mmap的方式+多进程读写，优化性能。

**Comment by pqpo** [comment]
关于进程锁新开了一坑：[PLock](https://github.com/pqpo/PLock)

**Comment by lightai** [comment]
666，我看看
