### ISSUE TITLE
内存写坏了？

### ISSUE THREAD

**Issue by andyken** [pqpo/Log4a#9]
Build fingerprint: 'Xiaomi/markw/markw:6.0.1/MMB29M/8.1.4:user/release-keys'
Revision: '0'
ABI: 'arm'
pid: 29161, tid: 29161, name: xxx  >>> xxxx <<<
signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xf412e000
    r0 f412d005  r1 f412e000  r2 70795464  r3 6e273d65
    r4 ffb0e9c8  r5 f412d005  r6 ab33da20  r7 ffb0e990
    r8 ab339670  r9 00001000  sl 00000022  fp 00001000
    ip 00000000  sp ffb0e988  lr dfb3c5f7  pc f7328ff8  cpsr 600d0030

backtrace:
    #00 pc 00017ff8  /system/lib/libc.so (strlen+71)
    #01 pc 000095f3  /data/app/xxx/lib/arm/liblog4a-lib.so (_ZN9LogBufferC1EPcj+38)
    #02 pc 0000939d  /data/app/xxx/lib/arm/liblog4a-lib.so
    #03 pc 000ea9c9  /system/lib/libart.so (art_quick_generic_jni_trampoline+40)
    #04 pc 000e62d1  /system/lib/libart.so (art_quick_invoke_stub_internal+64)
    #05 pc 003eb9c5  /system/lib/libart.so (art_quick_invoke_static_stub+172)
    #06 pc 007fac2c  [stack]

**Comment by pqpo** [comment]
看样子是的，有复现场景不？

**Comment by andyken** [comment]
不是必现的，目前在红米4 Android6.0和谷歌NexusAndroid7.0虚拟机各出现了一次

**Comment by pqpo** [comment]
是 v1.1.0 版本吗？

**Comment by pqpo** [comment]
新版本待观察
